### ISSUE TITLE
(Fix) rename repo and 

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/solidity-flattener#23]
Problem:

- repo has `oracles` in the name
- combine-solidity is not 
Solutions:
- remove oracles. not sure if we need to add poa- prefix

@rstormsf what do you think will be a good name?
`solidity-flattener` is taken

`solc-flattener` ?

**Comment by vbaranov** [comment]
As for me, I like `solc-js-flattener`

**Comment by igorbarinov** [comment]
js is not important here
solc is known by fewer people than solidity
let's use solidity-flattener
